Base:
    model_root: './checkpoints/'
    num_workers: 3
    verbose: 1
    patience: 3
    save_best_only: True
    eval_interval_epochs: 1
    debug_mode: False

SimpleX_movielens1m_m1:
    model: SimpleX
    dataset_id: movielens1m_m1_8de87281
    metrics: ['F1(k=20)', 'NDCG(k=20)', 'Recall(k=20)', 'NDCG(k=50)', 'Recall(k=50)', 'HitRate(k=20)', 'HitRate(k=50)']
    optimizer: adam
    learning_rate: 1.e-3
    batch_size: 1024
    num_negs: 1500
    embedding_dim: 128
    aggregator: mean
    gamma: 0.8
    user_id_field: user_id
    item_id_field: item_id
    user_history_field: user_history
    embedding_regularizer: 1.e-5
    net_regularizer: 0
    net_dropout: 0.4
    attention_dropout: 0
    enable_bias: True
    similarity_score: cosine
    loss: CosineContrastiveLoss
    margin: 0.9
    negative_weight: 10
    sampling_num_process: 4
    fix_sampling_seeds: True
    ignore_pos_items: True
    epochs: 100
    shuffle: True
    seed: 2019
    monitor: 'NDCG(k=20)'
    monitor_mode: 'max'
    